### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by TabulateJarl8** [realiti4/pip-upgrade#11]
Hey, I decided to update my packages today, and got a KeyError. Here's the full traceback:

```py
[tabulate@xenon ~]$ pip-upgrade
Checking outdated packages...
Skipping dulwich, warning: Name mismatch. This will be improved. Manually upgrade if needed
Traceback (most recent call last):
  File "/home/tabulate/.local/bin/pip-upgrade", line 8, in <module>
    sys.exit(main())
  File "/home/tabulate/.local/lib/python3.9/site-packages/pip_upgrade/main.py", line 98, in main
    pip_upgrade.get_dependencies()
  File "/home/tabulate/.local/lib/python3.9/site-packages/pip_upgrade/dependencies_base.py", line 35, in get_dependencies
    pkg_store = self.dict[pkg_name]
KeyError: 'Panda3D'
```

Version: 0.5.1
OS: Manjaro (Linux 5.10.60)

Note: This issue is resolved if I manually upgrade Panda3D.

**Comment by realiti4** [comment]
Hi, thanks for pointing this out. Cases didn't match for Panda3D. Stored name and pkg_name were different for some reason. Here I applied a quick fix 578885d6206159b939c. I also bumped the version to 0.5.2, should be available on pypi soon too.

**Comment by realiti4** [comment]
I also checked dulwich, but didn't get the 'Name mismatch' warning on my end.

**Comment by TabulateJarl8** [comment]
The issue with Panda3D seems to have been fixed now, feel free to close this issue
