### ISSUE TITLE
pycairo does not upgrade 

### ISSUE THREAD

**Issue by ferreirafm** [realiti4/pip-upgrade#15]
Hi devs, 
I'm experienced troubles with pycairo update. The error message is as follows:
...
Updating 1 of 15 packages: pycairo
bpyutils | 2023-07-13 17:32:50,731 | INFO | Executing command: /usr/local/bin/pip install pycairo --no-cache-dir --upgrade
Requirement already satisfied: pycairo in /usr/lib/python3/dist-packages (1.16.2)
Collecting pycairo
  Downloading pycairo-1.24.0.tar.gz (344 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 344.9/344.9 kB 5.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pycairo
  Building wheel for pycairo (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycairo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/cairo
      copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-39/cairo
      copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-39/cairo
      copying cairo/py.typed -> build/lib.linux-x86_64-cpython-39/cairo
      running build_ext
      Package cairo was not found in the pkg-config search path.
      Perhaps you should add the directory containing `cairo.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'cairo' found
      Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycairo
Failed to build pycairo
ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/__init__.py", line 79, in command
    return _command(**ARGUMENTS)
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/__init__.py", line 258, in _command
    update_registry(registry, yes = a.yes, user = a.user, check = a.check,
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/commands/helper.py", line 301, in update_registry
    _pip.call("install", package.name,
  File "/usr/local/lib/python3.9/dist-packages/pipupgrade/_pip.py", line 79, in call
    output = popen(*params, output = output, raise_err = raise_err)
  File "/usr/local/lib/python3.9/dist-packages/bpyutils/util/system.py", line 126, in popen
    raise PopenError(code, command)
bpyutils.exception.PopenError: Command '/usr/local/bin/pip install pycairo --no-cache-dir --upgrade' returned non-zero exit status 1.

An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues

...

**Comment by realiti4** [comment]
Hello, thank you for your input.

First of all, could you please confirm that you are using this package realiti4/pip-upgrade and not achillesrasquinhar/pipupgrade? Because your error message belongs to that. You can run our package with `pip-upgrade`

This issue looks like not related to upgrade tools, but missing libs or compiler to build pycairo. I find this solution after a quick search, and you might want to try to install `sudo apt install libcairo2-dev pkg-config python3-dev` first. Let me know if this helps. Again you might find better help if you search your issue on google, since this a building from source issue. You can also try conda.

**Comment by ferreirafm** [comment]
The problem has been solved. I uninstalled the old pipupgrade, installed pip-upgrade and solved some dependencies. 
Thanks for helping.

**Comment by realiti4** [comment]
Happy to hear the problem is solved.
