### ISSUE TITLE
wishlist: option to automatically accept the upgrade prompt

### ISSUE THREAD

**Issue by slippycheeze** [realiti4/pip-upgrade#9]
g'day.  it'd be nice to be able to automatically accept whatever upgrades were found; with version control tracking changes in installed packages it is easy for me to roll back an update that causes troubles.   something like `--yes` that acted as if I said `y` at the prompt.

**Comment by realiti4** [comment]
Hi, thanks for the suggestion. I added the option to skip user promt here c8b245c0a71896a1. Use `--yes` or `-y`. You can install from master now. I'll upgrade the release soon as well, finishing some changes, so it should be avaliable on pypi too.
